language: python
python:
    - '3.5'
sudo: false
cache:
    directories:
        - "$HOME/.cache/pip"
install:
    - pip install pipenv flake8
    - pipenv install
script:
    - pipenv run flake8 --max-line-length=150 --exclude=venv,*/migrations/* .
    - pipenv run ./manage.py test
