language: python
python:
    - '3.5'
sudo: false
cache:
    directories:
        - "$HOME/.cache/pip"
install:
    - pip install pip flake8 -r requirements.txt
script:
    - flake8 --max-line-length=150 --exclude=venv,*/migrations/* .
    - ./manage.py test
