# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RatingField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('numerical', 'Numerical'), ('multiple_choice', 'Multiple choice')], max_length=16)),
                ('prompt', models.CharField(max_length=64)),
                ('min_number', models.IntegerField(default=-1)),
                ('max_number', models.IntegerField(default=-1)),
                ('options', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='RatingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathons', models.ManyToManyField(related_name='readers', to='director.Hackathon')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='director.Organization')),
            ],
        ),
    ]
