# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='registration.Application')),
            ],
        ),
        migrations.CreateModel(
            name='RatingField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'numerical', b'Numerical'), (b'multiple_choice', b'Multiple choice')], max_length=16)),
                ('prompt', models.CharField(max_length=64)),
                ('min_number', models.IntegerField(default=-1)),
                ('max_number', models.IntegerField(default=-1)),
                ('options', models.TextField(default=b'')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reader.Rating')),
            ],
        ),
        migrations.CreateModel(
            name='RatingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='registration.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathons', models.ManyToManyField(related_name='readers', to='director.Hackathon')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='director.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='reader.Reader'),
        ),
    ]
