# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingfield',
            name='options',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
