# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20180407_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='user',
        ),
        migrations.AlterField(
            model_name='ratingresponse',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
