# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 20:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20180201_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingresponse',
            name='data',
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='rating_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
