# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180408_0152'),
        ('reader', '0003_auto_20180408_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingresponse',
            name='applicant',
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='application',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='application.Application'),
            preserve_default=False,
        ),
    ]
