# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20180408_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='application',
        ),
        migrations.RemoveField(
            model_name='ratingfield',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingField',
        ),
    ]
