# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_auto_20180428_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingResponse',
            new_name='Rating',
        ),
    ]
