# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 12:39
from __future__ import unicode_literals

from django.db import migrations


def create_default_rating_fields(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    RatingField = apps.get_model("reader", "RatingField")
    RatingField.objects.using(db_alias).create(name="skill", weight=50)
    RatingField.objects.using(db_alias).create(name="community", weight=25)
    RatingField.objects.using(db_alias).create(name="passion", weight=25)


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_auto_20180508_1202'),
    ]

    operations = [
        migrations.RunPython(create_default_rating_fields)
    ]
