# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('check_in', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInGroup',
            fields=[
                ('checked_in', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checkinevent',
            name='check_in_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.CheckInGroup'),
        ),
    ]
