# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkingroup',
            old_name='uuid',
            new_name='id',
        ),
    ]
