# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='show_in_maps',
            field=models.BooleanField(default=False),
        ),
    ]
