# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('entry_code', models.CharField(max_length=64)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[(b'preparing', b'Preparing'), (b'open', b'Open'), (b'closed', b'Closed')], max_length=16)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='director.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('type', models.CharField(choices=[(b'multiple_choice', b'Multiple Choice'), (b'multiple_choice_other', b'Multiple Choice with Other'), (b'short_answer', b'Short Answer'), (b'long_answer', b'Long Answer')], max_length=32)),
                ('prompt', models.CharField(max_length=256)),
                ('options', models.TextField(default=b'')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='registration.Application')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='registration.Application'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='director.Hackathon'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='registration.ApplicantTeam'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
