# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Hackathon_Application',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_username',
        ),
    ]
