# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-07 15:19
from __future__ import unicode_literals

import apps.registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicant',
            managers=[
                ('objects', apps.registration.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='github_user_name',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
    ]
