# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_drip_email',
            field=models.BooleanField(default=False),
        ),
    ]
