# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-07 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180407_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='github_user_name',
            new_name='github_username',
        ),
    ]
