# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171113_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfield',
            name='char_limit',
            field=models.IntegerField(default=256),
        ),
    ]
