# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_applicationfield_char_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='github_user_name',
            field=models.CharField(blank=True, max_length=39, null=True, unique=True),
        ),
    ]
