# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_applicant_github_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('open', 'Open'), ('closed', 'Closed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='options',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_choice_other', 'Multiple Choice with Other'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer')], max_length=32),
        ),
    ]
