# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180106_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantteam',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='applicationfield',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='data',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='team',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hackathon',
        ),
        migrations.DeleteModel(
            name='ApplicantTeam',
        ),
        migrations.DeleteModel(
            name='ApplicationField',
        ),
    ]
