# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180126_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(help_text='Required', max_length=200, unique=True),
        ),
    ]
