# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180126_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='username',
        ),
    ]
