# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-28 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(db_index=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SA', 'Saved'), ('SU', 'Submitted')], default='SA', max_length=2)),
                ('github_username', models.CharField(blank=True, max_length=39, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('admission_status', models.CharField(choices=[('A', 'Admitted'), ('W', 'Waitlisted'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='application.Application')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('application', 'question_id')]),
        ),
    ]
