# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-28 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='github',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='github',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='submission',
            name='devpost',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='submission',
            name='essay_helped',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='submission',
            name='essay_project',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='submission',
            name='linkedin',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='submission',
            name='personal_website',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
