# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
