# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-31 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180529_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('no_answer', 'Prefer not to answer')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('no_answer', 'Prefer not to answer')], max_length=16),
        ),
    ]
