# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_length',
            field=models.IntegerField(default=65535),
        ),
    ]
