# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-22 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_auto_20180531_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_status', models.CharField(choices=[('admitted', 'Admitted'), ('denied', 'Denied'), ('pending', 'Pending'), ('waitlisted', 'Waitlisted')], default='pending', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
