# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_question_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
