# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-16 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='priority',
        ),
    ]
