# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_question_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
