# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20180508_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SA', 'Saved'), ('SU', 'Submitted')], default='SA', max_length=2),
        ),
    ]
