# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20180509_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='application.Application')),
            ],
        ),
    ]
