# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20180516_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='application.Application'),
        ),
    ]
