# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20180516_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='filename',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
