# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_question_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False, help_text='Indicates whether users are required to fill out this question before submitting the application.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(help_text='Indicates what kind of input this question accepts (ex: short response, text field, etc).', max_length=255),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question'),
        ),
    ]
