# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20180523_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admission_status',
            field=models.CharField(choices=[('A', 'Admitted'), ('W', 'Waitlisted'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=2),
        ),
    ]
