# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20180528_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(db_index=True, default=-1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('application', 'question_id')]),
        ),
    ]
