# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_applicant_github_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
